### ISSUE TITLE
我的这个train训练显示填充函数未实现，是为什么呢？

### ISSUE THREAD

**Issue by nnnnnnml** [YaoZhang93/mmFormer#18]
Traceback (most recent call last):
  File "/media/jxust/磁盘2/mmFormer-main/mmformer/train.py", line 248, in <module>
    main()
  File "/media/jxust/磁盘2/mmFormer-main/mmformer/train.py", line 166, in main
    fuse_pred, sep_preds, prm_preds = model(x, mask)
  File "/home/jxust/anaconda3/envs/nnformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jxust/anaconda3/envs/nnformer/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jxust/anaconda3/envs/nnformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/jxust/磁盘2/mmFormer-main/mmformer/mmformer.py", line 361, in forward
    flair_x1, flair_x2, flair_x3, flair_x4, flair_x5 = self.flair_encoder(x[:, 0:1, :, :, :])
  File "/home/jxust/anaconda3/envs/nnformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/jxust/磁盘2/mmFormer-main/mmformer/mmformer.py", line 40, in forward
    x1 = self.e1_c1(x)
  File "/home/jxust/anaconda3/envs/nnformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jxust/anaconda3/envs/nnformer/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 569, in forward
    return F.conv3d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
  File "/home/jxust/anaconda3/envs/nnformer/lib/python3.6/site-packages/torch/nn/functional.py", line 3581, in _pad
    raise NotImplementedError
NotImplementedError

**Comment by YaoZhang93** [comment]
可能是pytorch版本的问题，可以用我提供的pytorch版本，我试过pytorch>2.0也是可以的。

**Comment by nnnnnnml** [comment]
想问一下是单卡还是多卡呢，我看论文是单卡17G，我用RTX3090 24G单卡显示爆显存，是为什么呢？能解答一下吗
